# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "ethereum_models"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "ethereum"

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["dbt_packages/fsc_evm/doc_descriptions", "models/doc_descriptions", "models"]
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"
  - "dbt_packages"

tests:
  +store_failures: true # all tests

on-run-start:
  - "{{ create_sps() }}"
  - "{{ create_udfs() }}"

on-run-end:
  - '{{ apply_meta_as_tags(results) }}'

dispatch:
  - macro_namespace: dbt
    search_order:
      - ethereum-models
      - dbt_snowflake_query_tags
      - dbt

query-comment:
  comment: '{{ dbt_snowflake_query_tags.get_query_comment(node) }}'
  append: true # Snowflake removes prefixed comments.

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  ethereum_models: # replace with the name of the chain
    +copy_grants: true
    +persist_docs:
      relation: true
      columns: true
    +on_schema_change: "append_new_columns"
    +meta:
      disallow-spaces-in-resource-names: true
      source-freshness-run-project-hooks: true
  livequery_models:
    +materialized: ephemeral
  fsc_evm:
    +enabled: false # disable fsc_evm package by default
    +copy_grants: true
    +persist_docs:
      relation: true
      columns: true
    +on_schema_change: "append_new_columns"
    +post-hook: "{{ fsc_evm.enable_change_tracking() }}"
    main_package:
      +enabled: false # disable top level package by default, enabled subpackages as needed
      admin:
        +enabled: true
      core:
        +enabled: true # enable subpackages, as needed
      github_actions:
        +enabled: true
      labels:
        +enabled: true
      observability:
        +enabled: true
      prices:
        +enabled: true
      token_reads:
        +enabled: true
      utils:
        +enabled: true
    decoder_package:
      +enabled: false
      abis:
        +enabled: true
      decoded_logs:
        +enabled: true
    curated_package:
      +enabled: false
      defi:
        +enabled: false
        bridge:
          +enabled: true
        dex:
          +enabled: true
        lending:
          +enabled: true
        stablecoins:
          +enabled: true
      stats:
        +enabled: true
      chain_stats:
        +enabled: true
    balances_package:
      +enabled: false
      erc20:
        +enabled: true
      native:
        +enabled: true
    scores_package:
      +enabled: true

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.

vars:
  "dbt_date:time_zone": GMT
  STREAMLINE_INVOKE_STREAMS: false
  STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES: false
  UPDATE_UDFS_AND_SPS: false
  STREAMLINE_RUN_HISTORY: false
  UPDATE_SNOWFLAKE_TAGS: true
  WAIT: 0
  HEAL_MODEL: false
  HEAL_MODELS: []
  LOAD_CUSTOM_FUNCTIONS: false

#### STREAMLINE 2.0 BEGIN ####

  API_INTEGRATION: '{{ var("config")[target.name]["API_INTEGRATION"] if var("config")[target.name] else var("config")["dev"]["API_INTEGRATION"] }}'
  EXTERNAL_FUNCTION_URI: '{{ var("config")[target.name]["EXTERNAL_FUNCTION_URI"] if var("config")[target.name] else var("config")["dev"]["EXTERNAL_FUNCTION_URI"] }}'
  ROLES: |
    ["INTERNAL_DEV"]

  config:
  # The keys correspond to dbt profiles and are case sensitive
    dev:
      API_INTEGRATION: AWS_ETHEREUM_API_STG_V2
      EXTERNAL_FUNCTION_URI: p6h6x0ncl1.execute-api.us-east-1.amazonaws.com/stg/
      ROLES:
        - AWS_LAMBDA_ETHEREUM_API
        - INTERNAL_DEV

    prod:
      API_INTEGRATION: AWS_ETHEREUM_API_PROD_V2
      EXTERNAL_FUNCTION_URI: z8x7p0tevi.execute-api.us-east-1.amazonaws.com/prod/
      ROLES:
        - AWS_LAMBDA_ETHEREUM_API
        - INTERNAL_DEV
        - DBT_CLOUD_ETHEREUM

#### STREAMLINE 2.0 END ####
flags:
  require_generic_test_arguments_property: true