version: 2

sources:
  - name: ethereum_external_bronze
    schema: bronze
    loader: S3
    tables:
      - name: token_balances
        description: "External table of NFT metadata files"
        external:
          location: "@{{ target.database }}.bronze.analytics_external_tables/{{ target.database }}/TOKEN_BALANCES"
          file_format: "( type = json, strip_outer_array = TRUE )"
          auto_refresh: false
          partitions:
            - name: _partition_by_block_id
              data_type: integer
              expression: to_number(split_part(metadata$filename, '/', 3))
        columns:
          - name: address
            data_type: string
            description: "address with balance"
            expression: value:address::string
          - name: contract_address
            data_type: string
            description: "token contract address"
            expression: value:contract_address::string
          - name: block_number
            data_type: number
            description: "block height"
            expression: value:block_number
          - name: metadata
            data_type: variant
            description: "api call metadata"
            expression: value:metadata::variant
          - name: data
            data_type: variant
            description: "raw response from api call"
            expression: value:data::variant
