{% macro grant_data_share_statements() %}
  {% if target.database == 'ETHEREUM' %}
    GRANT SELECT ON TABLE "ETHEREUM"."CORE"."DIM_DATES" TO SHARE "FLIPSIDE_ETHEREUM";
    GRANT SELECT ON TABLE "ETHEREUM"."CORE"."EZ_DEX_SWAPS" TO SHARE "FLIPSIDE_ETHEREUM";
    GRANT SELECT ON TABLE "ETHEREUM"."CORE"."EZ_NFT_MINTS" TO SHARE "FLIPSIDE_ETHEREUM";
    GRANT SELECT ON TABLE "ETHEREUM"."CORE"."EZ_TOKEN_TRANSFERS" TO SHARE "FLIPSIDE_ETHEREUM";
    GRANT SELECT ON VIEW "ETHEREUM"."CORE"."SV_DIM_CONTRACTS" TO SHARE "FLIPSIDE_ETHEREUM";
    GRANT SELECT ON VIEW "ETHEREUM"."CORE"."SV_DIM_DEX_LIQUIDITY_POOLS" TO SHARE "FLIPSIDE_ETHEREUM";
    GRANT SELECT ON VIEW "ETHEREUM"."CORE"."SV_DIM_EVENT_SIGNATURES" TO SHARE "FLIPSIDE_ETHEREUM";
    GRANT SELECT ON VIEW "ETHEREUM"."CORE"."SV_DIM_FUNCTION_SIGNATURES" TO SHARE "FLIPSIDE_ETHEREUM";
    GRANT SELECT ON VIEW "ETHEREUM"."CORE"."SV_DIM_LABELS" TO SHARE "FLIPSIDE_ETHEREUM";
    GRANT SELECT ON VIEW "ETHEREUM"."CORE"."SV_EZ_NFT_SALES" TO SHARE "FLIPSIDE_ETHEREUM";
    GRANT SELECT ON VIEW "ETHEREUM"."CORE"."SV_EZ_NFT_TRANSFERS" TO SHARE "FLIPSIDE_ETHEREUM";
    GRANT SELECT ON VIEW "ETHEREUM"."CORE"."SV_FACT_BLOCKS" TO SHARE "FLIPSIDE_ETHEREUM";
    GRANT SELECT ON VIEW "ETHEREUM"."CORE"."SV_FACT_EVENT_LOGS" TO SHARE "FLIPSIDE_ETHEREUM";
    GRANT SELECT ON VIEW "ETHEREUM"."CORE"."SV_FACT_HOURLY_TOKEN_PRICES" TO SHARE "FLIPSIDE_ETHEREUM";
    GRANT SELECT ON VIEW "ETHEREUM"."CORE"."SV_FACT_TOKEN_TRANSFERS" TO SHARE "FLIPSIDE_ETHEREUM";
    GRANT SELECT ON VIEW "ETHEREUM"."CORE"."SV_FACT_TRACES" TO SHARE "FLIPSIDE_ETHEREUM";
    GRANT SELECT ON VIEW "ETHEREUM"."CORE"."SV_FACT_TRANSACTIONS" TO SHARE "FLIPSIDE_ETHEREUM";
  {% else %}
    select 1; -- hooks will error if they don't have valid SQL in them, this handles that!
  {% endif %}
{% endmacro %}