# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "ethereum_models"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "ethereum"

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["/dev/null"]
test-paths: ["/dev/null"]
seed-paths: ["/dev/null"]
macro-paths: ["/dev/null"]
snapshot-paths: ["/dev/null"]

target-path: "../target_bronze" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "../target_bronze"
  - "dbt_modules"
  - "dbt_packages"

models:
  +copy_grants: true
  +on_schema_change: sync_all_columns

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.

vars:
  "dbt_date:time_zone": GMT
