name: dbt_run_nft_reads
run-name: dbt_run_nft_reads

on:
  workflow_dispatch:
  schedule:
    # At minute 0. (see https://crontab.guru)
    - cron: "0 * * * *"

concurrency:
  group: ${{ github.workflow }}

jobs:
  called_workflow_template:
    uses: FlipsideCrypto/fsc-evm/.github/workflows/dbt_run_template.yml@pre-release/v4-beta
    with:
      command_name: Run Curated Models
      command: |
        dbt run -m "ethereum_models,tag:nft_reads"
    secrets: inherit
