name: dbt_run_integration_test
run-name: ${{ github.event.inputs.branch }}

on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}

jobs:
  called_workflow_template:
    uses: FlipsideCrypto/evm-models-templates/.github/workflows/dbt_integration_test.yml@main
    with:
      command: >
        dbt test --selector 'integration_tests'
      environment:  ${{ github.ref == 'refs/heads/main' && 'workflow_prod' || 'workflow_dev' }}
      warehouse: ${{ vars.WAREHOUSE }}
    secrets: inherit