name: dbt_run_integration_test
run-name: ${{ github.event.inputs.branch }}

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: string

concurrency: ${{ github.workflow }}

jobs:
  called_workflow_template:
    uses: FlipsideCrypto/evm-models-template/.github/workflows/dbt_integration_test.yml@main
    with:
      command: >
        dbt test --selector 'integration_tests'
      environment: ${{ inputs.environment }}
      warehouse: ${{ vars.WAREHOUSE }}
    secrets: inherit