name: dbt_alter_all_gha_tasks
run-name: dbt_alter_all_gha_tasks

on:
  workflow_dispatch:
    branches:
      - "main"
    inputs:
      task_action:
        type: choice 
        description: Action to perform on all tasks
        required: true
        options:
          - RESUME
          - SUSPEND
        default: RESUME

concurrency:
  group: ${{ github.workflow }}

jobs:
  called_workflow_template:
    uses: FlipsideCrypto/fsc-evm/.github/workflows/dbt_run_template_alter_all_gha_tasks.yml@main
    with:
      task_action: ${{ inputs.task_action }}
      target: prod
    secrets: inherit