name: dbt_alter_gha_tasks
run-name: dbt_alter_gha_tasks

on:
  workflow_dispatch:
    branches:
      - "main"
    inputs:
      workflow_name:
        type: string
        description: Name of the workflow to perform the action on, no .yml extension
        required: true
      task_action:
        type: choice 
        description: Action to perform
        required: true
        options:
          - SUSPEND
          - RESUME
        default: SUSPEND

concurrency:
  group: ${{ github.workflow }}

jobs:
  called_workflow_template:
    uses: FlipsideCrypto/fsc-evm/.github/workflows/dbt_run_template_alter_gha_tasks.yml@main
    with:
      workflow_name: ${{ inputs.workflow_name }}
      task_action: ${{ inputs.task_action }}
      target: prod
    secrets: inherit