name: dbt_run_streamline_beacon_chain_history
run-name: dbt_run_streamline_beacon_chain_history

on:
  workflow_dispatch:
  schedule:
    # Runs "at 7:00 UTC" (see https://crontab.guru)
    - cron: '0 7 * * *'
    
env:
  DBT_PROFILES_DIR: ./

  ACCOUNT: "${{ vars.ACCOUNT }}"
  ROLE: "${{ vars.ROLE }}"
  USER: "${{ vars.USER }}"
  PASSWORD: "${{ secrets.PASSWORD }}"
  REGION: "${{ vars.REGION }}"
  DATABASE: "${{ vars.DATABASE }}"
  WAREHOUSE: "${{ vars.WAREHOUSE }}"
  SCHEMA: "${{ vars.SCHEMA }}"

concurrency:
  group: ${{ github.workflow }}

jobs:
  run_dbt_jobs:
    runs-on: ubuntu-latest
    environment: 
      name: workflow_prod

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"

      - name: install dependencies
        run: |
          pip3 install dbt-snowflake==${{ vars.DBT_VERSION }} cli_passthrough requests click
          dbt deps
      - name: Run DBT Jobs
        run: |
          dbt run --vars '{"STREAMLINE_INVOKE_STREAMS":True}' -m 1+models/silver/streamline/streamline__beacon_validators_history.sql 1+models/silver/streamline/streamline__beacon_validator_balances_history.sql 1+models/silver/streamline/streamline__beacon_committees_history.sql 1+models/silver/streamline/streamline__beacon_sync_committees_history.sql