name: dbt_test_intraday
run-name: dbt_test_intraday

on:
  workflow_dispatch:
    branches:
      - "main"
    
concurrency:
  group: ${{ github.workflow }}

jobs:
  called_workflow_template:
    uses: FlipsideCrypto/fsc-evm/.github/workflows/dbt_run_template.yml@pre-release/v4-beta
    with:
      target: test
      command_name: Run Observability & Recent Tests
      command: |
        dbt run -m "fsc_evm,tag:observability"
        dbt test -m "fsc_evm,tag:recent_test"
    secrets: inherit