name: dbt_run_scheduled_bi_hourly
run-name: dbt_run_scheduled_bi_hourly

on:
  workflow_dispatch:
  schedule:
    # Runs "every 2 hours" (see https://crontab.guru)
    - cron: '0 */2 * * *'
    
env:
  DBT_PROFILES_DIR: ./

  ACCOUNT: "${{ vars.ACCOUNT }}"
  ROLE: "${{ vars.ROLE }}"
  USER: "${{ vars.USER }}"
  PASSWORD: "${{ secrets.PASSWORD }}"
  REGION: "${{ vars.REGION }}"
  DATABASE: "${{ vars.DATABASE }}"
  WAREHOUSE: "BACKFILL"
  SCHEMA: "${{ vars.SCHEMA }}"

concurrency:
  group: ${{ github.workflow }}

jobs:
  run_dbt_jobs:
    runs-on: ubuntu-latest
    environment: 
      name: workflow_prod

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"

      - name: install dependencies
        run: |
          pip3 install dbt-snowflake==${{ vars.DBT_VERSION }} cli_passthrough requests click
          dbt deps
      - name: Run DBT Jobs Beacon Chain Updates
        run: |
          dbt run -m models/beacon_chain 
      - name: Run DBT Jobs Complete Beacon Chain Streamline 
        run: |
          dbt run -m ./models/silver/streamline/streamline__complete_beacon_committees.sql ./models/silver/streamline/streamline__complete_beacon_sync_committees.sql ./models/silver/streamline/streamline__complete_beacon_validators.sql ./models/silver/streamline/streamline__complete_beacon_validator_balances.sql

