name: dbt_run_streamline_reads
run-name: dbt_run_streamline_reads

on:
  workflow_dispatch:
  schedule:
    # Runs “At minute 40 past every 2nd hour from 1 through 23.” (see https://crontab.guru)
    - cron: "40 1-23/2 * * *"

jobs:
  called_workflow_template:
    uses: FlipsideCrypto/fsc-evm/.github/workflows/dbt_run_template.yml@pre-release/v4-beta
    with:
      command_name: Run History Models
      command: |
        dbt run --vars '{"STREAMLINE_INVOKE_STREAMS":True}' -m "ethereum_models,tag:streamline_reads_curated" "ethereum_models,tag:streamline_reads_realtime" "ethereum_models,tag:streamline_reads_complete"
    secrets: inherit
