name: dbt_run_streamline_reads
run-name: dbt_run_streamline_reads

on:
  workflow_dispatch:
    branches:
      - "main"

jobs:
  called_workflow_template:
    uses: FlipsideCrypto/fsc-evm/.github/workflows/dbt_run_template.yml@prod/v4.x
    with:
      command_name: Run History Models
      command: |
        dbt run --vars '{"STREAMLINE_INVOKE_STREAMS":True}' -m "ethereum_models,tag:streamline_reads_curated" "ethereum_models,tag:streamline_reads_realtime" "ethereum_models,tag:streamline_reads_complete"
    secrets: inherit
