name: dbt_run_nft_list
run-name: dbt_run_nft_list

on:
  workflow_dispatch:
  schedule:
    # At minute 0 past hour 0 and 12. (see https://crontab.guru)
    - cron: "0 0,12 * * *"

concurrency:
  group: ${{ github.workflow }}

jobs:
  called_workflow_template:
    uses: FlipsideCrypto/fsc-evm/.github/workflows/dbt_run_template.yml@pre-release/v4-beta
    with:
      command_name: Run Curated Models
      command: |
        dbt run -m "ethereum_models,tag:nft_list"
    secrets: inherit