name: dbt_run_nft_list
run-name: dbt_run_nft_list

on:
  workflow_dispatch:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}

jobs:
  called_workflow_template:
    uses: FlipsideCrypto/fsc-evm/.github/workflows/dbt_run_template.yml@prod/v4.x
    with:
      command_name: Run Curated Models
      command: |
        dbt run -m "ethereum_models,tag:nft_list"
    secrets: inherit