name: dbt_run_adhoc
run-name: ${{ inputs.dbt_command }}

on:
  workflow_dispatch:
    branches:
      - "main"
    inputs:
      target:
        type: choice 
        description: DBT Run Environment
        required: true
        options:
          - dev
          - prod
        default: dev
      warehouse:
        type: choice 
        description: Snowflake warehouse
        required: true 
        options:
          - DBT
          - DBT_CLOUD
          - DBT_EMERGENCY
          - DBT_MEGA
        default: DBT
      dbt_command:
        type: string
        description: 'DBT Run Command'
        required: true
    
concurrency:
  group: ${{ github.workflow }}

jobs:
  called_workflow_template:
    uses: FlipsideCrypto/fsc-evm/.github/workflows/dbt_run_template.yml@main
    with:
      warehouse: ${{ inputs.warehouse }}
      target: ${{ inputs.target }}
      command_name: Run DBT Command
      command: ${{ inputs.dbt_command }}
    secrets: inherit