version: 2

sources:
  - name: bronze_streamline
    database: streamline
    schema: |
      {{ target.database.upper() | replace('_DEV', '') ~ '_DEV' if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else target.database.upper() | replace('_DEV', '') }}
    tables:
      - name: receipts
      - name: blocks
      - name: transactions
      - name: traces
      - name: decoded_logs
      - name: confirm_blocks
      - name: contract_abis
      - name: beacon_blocks_v2
      - name: beacon_validators_v2
      - name: beacon_validator_balances
      - name: beacon_blobs_v2
      - name: nft_metadata_api
      - name: reads_v2
      - name: token_balances_v2
      - name: eth_balances_v2
      - name: decoded_traces_v2
      - name: token_reads
      - name: pending_deposits
      - name: pending_partial_withdrawals
      - name: pending_consolidations
      - name: balances_erc20
      - name: balances_native
      - name: stablecoin_reads
  - name: crosschain_silver
    database: >-
      {{ 'CROSSCHAIN_DEV' if '_DEV' in target.database.upper() else 'CROSSCHAIN' }}
    schema: silver
    tables:
      - name: near_address_encoded
      - name: labels_combined
      - name: complete_provider_asset_metadata
      - name: complete_native_asset_metadata
      - name: complete_native_prices
      - name: complete_provider_prices
      - name: complete_token_asset_metadata
      - name: complete_token_prices
      - name: tokens_stablecoins
  - name: ethereum_silver
    database: ethereum
    schema: silver
    tables:
      - name: base_state_hashes
  - name: crosschain_public
    database: crosschain
    schema: bronze_public
    tables:
      - name: user_abis
      - name: user_metadata
  - name: ethereum_silver
    database: ethereum
    schema: silver
    tables:
      - name: token_meta_backup
      - name: snapshot_voting
      - name: snapshot_network
      - name: evm_chains_20221212
      - name: nft_metadata_legacy
      - name: nft_collection_metadata
      - name: eth_balance_diffs
      - name: token_balance_diffs
  - name: complete_streamline
    database: "{{ target.database }}"
    schema: streamline
    tables:
      - name: complete_contract_abis
  - name: github_actions
    database: "{{ target.database }}"
    schema: github_actions
    tables:
      - name: workflows
  - name: external_gold_defillama
    database: external
    schema: defillama
    tables:
      - name: dim_chains
  - name: abis_silver
    database: "{{ target.database }}"
    schema: silver
    tables:
      - name: verified_abis
      - name: complete_event_abis
  - name: fsc_evm_admin
    database: >-
      {{ 'FSC_EVM_DEV' if '_DEV' in target.database.upper() else 'FSC_EVM' }}
    schema: admin
    tables:
      - name: _master_keys
      - name: rpc_node_logs