version: 2

sources:
  - name: prod
    database: chainwalkers
    schema: prod
    tables:
      - name: ethereum_blocks
      - name: ethereum_txs
  - name: flipside_gold
    database: flipside_prod_db
    schema: ethereum
    tables:
      - name: contracts
      - name: labels
      - name: token_prices_hourly
  - name: flipside_silver
    database: flipside_prod_db
    schema: silver_ethereum
    tables:
      - name: contracts
      - name: reads
