version: 2

sources:
  - name: crosschain
    database: crosschain
    schema: core
    tables:
      - name: address_labels
      - name: dim_date_hours
      - name: ez_hourly_prices
  - name: eth_dev_db
    database: ethereum_dev
    schema: silver
    tables:
      - name: aave_atokens_upload
      - name: curve_pools_backfill
  - name: ethereum_bronze
    database: ethereum
    schema: bronze
    tables:
      - name: legacy_contracts
  - name: ethereum_silver
    database: ethereum
    schema: silver
    tables:
      - name: token_meta_backup
      - name: signatures_backfill
      - name: event_signatures_backfill
      - name: aave_atokens_upload
      - name: snapshot_voting
      - name: snapshot_network
      - name: evm_chains_20221212
      - name: nft_metadata_legacy
  - name: ethereum_share
    database: "{{target.database}}"
    schema: silver
    tables:
      - name: token_prices_hourly
      - name: dex_liquidity_pools
      - name: labels
  - name: bronze_streamline
    database: streamline
    schema: |
      {{ "ETHEREUM_DEV" if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else "ETHEREUM" }}
    tables:
      - name: beacon_blocks
      - name: blocks
      - name: beacon_committees
      - name: beacon_sync_committees
      - name: beacon_validators
      - name: beacon_validator_balances
      - name: contract_abis
      - name: decode_logs
      - name: eth_balances
      - name: nft_metadata_api
      - name: reads
      - name: sushi_rewards_schedule
      - name: token_balances
      - name: transactions
      - name: decoded_logs
      - name: receipts
      - name: traces
      - name: confirm_blocks
  - name: crosschain_silver
    database: crosschain
    schema: silver
    tables:
      - name: hourly_prices_coin_gecko
      - name: asset_metadata_coin_gecko
      - name: hourly_prices_coin_market_cap
      - name: asset_metadata_coin_market_cap
      - name: token_prices_priority_hourly
      - name: asset_metadata_priority
      - name: number_sequence
      - name: apis_keys
  - name: streamline_crosschain
    database: streamline
    schema: crosschain
    tables: 
      - name: node_mapping
  - name: eth_bronze_public
    database: ethereum
    schema: bronze_public
    tables:
      - name: user_abis
  - name: crosschain_public
    database: crosschain
    schema: bronze_public
    tables:
      - name: user_abis
  - name: streamline_test
    database: streamline
    schema: ethereum
    tables:
      - name: decoded_logs_test