version: 2

sources:
  - name: crosschain
    database: "{{ 'crosschain' if target.database == 'ETHEREUM' else 'crosschain_dev' }}"
    schema: core
    tables:
      - name: dim_date_hours
      - name: dim_labels
  - name: eth_dev_db
    database: ethereum_dev
    schema: silver
    tables:
      - name: aave_atokens_upload
      - name: curve_pools_backfill
  - name: ethereum_bronze
    database: ethereum
    schema: bronze
    tables:
      - name: legacy_contracts
  - name: ethereum_silver
    database: ethereum
    schema: silver
    tables:
      - name: token_meta_backup
      - name: snapshot_voting
      - name: snapshot_network
      - name: evm_chains_20221212
      - name: nft_metadata_legacy
      - name: nft_collection_metadata
      - name: eth_balance_diffs
      - name: token_balance_diffs
  - name: ethereum_share
    database: "{{target.database}}"
    schema: silver
    tables:
      - name: token_prices_hourly
      - name: dex_liquidity_pools
      - name: labels
  - name: bronze_streamline
    database: streamline
    schema: |
      {{ "ETHEREUM_DEV" if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else "ETHEREUM" }}
    tables:
      - name: beacon_blocks
      - name: beacon_blocks_v2
      - name: blocks
      - name: blocks_v2
      - name: beacon_committees
      - name: beacon_sync_committees
      - name: beacon_validators
      - name: beacon_validators_v2
      - name: beacon_validator_balances
      - name: contract_abis
      - name: contract_abis_v2
      - name: decode_logs
      - name: eth_balances
      - name: eth_balances_v2
      - name: nft_metadata_api
      - name: reads
      - name: reads_v2
      - name: sushi_rewards_schedule
      - name: token_balances
      - name: token_balances_v2
      - name: transactions
      - name: transactions_v2
      - name: decoded_logs
      - name: decoded_logs_v2
      - name: receipts
      - name: receipts_v2
      - name: traces
      - name: traces_v2
      - name: confirm_blocks
      - name: confirm_blocks_v2
      - name: decoded_traces
      - name: decoded_traces_v2
      - name: beacon_blobs_v2
  - name: crosschain_silver
    database: "{{ 'crosschain' if target.database == 'ETHEREUM' else 'crosschain_dev' }}"
    schema: silver
    tables:
      - name: near_address_encoded
      - name: labels_combined
      - name: complete_token_asset_metadata
      - name: complete_token_prices
      - name: complete_provider_asset_metadata
      - name: complete_provider_prices
      - name: complete_native_asset_metadata
      - name: complete_native_prices
  - name: eth_bronze_public
    database: ethereum
    schema: bronze_public
    tables:
      - name: user_abis
  - name: crosschain_public
    database: crosschain
    schema: bronze_public
    tables:
      - name: user_abis
      - name: user_metadata
  - name: streamline_test
    database: streamline
    schema: ethereum
    tables:
      - name: decoded_logs_test
  - name: external_gold_defillama
    database: external
    schema: defillama
    tables:
      - name: dim_chains
  - name: github_actions
    database: ethereum
    schema: github_actions
    tables:
      - name: workflows