version: 2

sources:
  - name: prod
    database: chainwalkers
    schema: prod
    tables:
      - name: ethereum_blocks
      - name: ethereum_txs
  - name: flipside_gold_ethereum
    database: flipside_prod_db
    schema: ethereum
    tables:
      - name: contracts
      - name: labels
      - name: token_prices_hourly
      - name: dex_liquidity_pools
      - name: nft_metadata
  - name: flipside_silver_ethereum
    database: flipside_prod_db
    schema: silver_ethereum
    tables:
      - name: contracts
      - name: reads
  - name: flipside_silver
    database: flipside_prod_db
    schema: silver
    tables:
      - name: ethereum_contracts_backfill
      - name: ethereum_contracts
  - name: eth_dev_db
    database: ethereum_dev
    schema: silver
    tables:
      - name: aave_atokens_upload
      - name: curve_pools_backfill
  - name: bronze
    database: flipside_prod_db
    schema: bronze
    tables:
      - name: prod_ethereum_sink_407559501
      - name: bronze_snapshot_719356055
  - name: ethereum_silver
    database: ethereum
    schema: silver
    tables:
      - name: token_meta_backup
      - name: signatures_backfill
      - name: event_signatures_backfill
      - name: aave_atokens_upload
      - name: snapshot_voting
      - name: snapshot_network
  - name: ethereum_share
    database: "{{target.database}}"
    schema: silver
    tables:
      - name: token_prices_hourly
      - name: dex_liquidity_pools
      - name: labels
  - name: bronze_streamline
    database: streamline
    schema: ethereum
    tables:
      - name: token_balances
      - name: eth_balances
      - name: reads
      - name: contract_abis
      - name: nft_metadata_api
      - name: sushi_rewards_schedule
      - name: blocks
      - name: transactions
      - name: beacon_blocks
