version: 2

sources:
  - name: prod
    database: chainwalkers
    schema: prod
    tables:
      - name: ethereum_blocks
      - name: ethereum_txs
  - name: flipside_gold_ethereum
    database: flipside_prod_db
    schema: ethereum
    tables:
      - name: contracts
      - name: token_prices_hourly
      - name: dex_liquidity_pools
      - name: nft_metadata
  - name: crosschain
    database: crosschain
    schema: core
    tables:
      - name: address_labels
      - name: dim_date_hours
  - name: flipside_silver_ethereum
    database: flipside_prod_db
    schema: silver_ethereum
    tables:
      - name: contracts
      - name: reads
  - name: flipside_silver
    database: flipside_prod_db
    schema: silver
    tables:
      - name: ethereum_contracts_backfill
      - name: ethereum_contracts
      - name: prices_v2
  - name: eth_dev_db
    database: ethereum_dev
    schema: silver
    tables:
      - name: aave_atokens_upload
      - name: curve_pools_backfill
  - name: bronze
    database: flipside_prod_db
    schema: bronze
    tables:
      - name: prod_ethereum_sink_407559501
      - name: bronze_snapshot_719356055
  - name: ethereum_silver
    database: ethereum
    schema: silver
    tables:
      - name: token_meta_backup
      - name: signatures_backfill
      - name: event_signatures_backfill
      - name: aave_atokens_upload
      - name: snapshot_voting
      - name: snapshot_network
  - name: ethereum_share
    database: "{{target.database}}"
    schema: silver
    tables:
      - name: token_prices_hourly
      - name: dex_liquidity_pools
      - name: labels
  - name: bronze_streamline
    database: streamline
    schema: |
      {{ "ETHEREUM_DEV" if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else "ETHEREUM" }}
    tables:
      - name: token_balances
      - name: eth_balances
      - name: reads
      - name: contract_abis
      - name: nft_metadata_api
      - name: sushi_rewards_schedule
      - name: blocks
      - name: transactions
      - name: beacon_blocks
      - name: committees
      - name: validators
  - name: crosschain_silver
    database: crosschain
    schema: silver
    tables:
      - name: hourly_prices_coin_gecko
      - name: asset_metadata_coin_gecko
      - name: hourly_prices_coin_market_cap
      - name: asset_metadata_coin_market_cap
  - name: streamline_crosschain
    database: streamline
    schema: crosschain
    tables: 
      - name: node_mapping
