version: 2

sources:
  - name: prod
    database: chainwalkers
    schema: prod
    tables:
      - name: ethereum_blocks
      - name: ethereum_txs
  - name: flipside_gold_ethereum
    database: flipside_prod_db
    schema: ethereum
    tables:
      - name: contracts
      - name: labels
      - name: token_prices_hourly
      - name: dex_liquidity_pools
      - name: nft_metadata
  - name: flipside_silver_ethereum
    database: flipside_prod_db
    schema: silver_ethereum
    tables:
      - name: contracts
      - name: reads
  - name: flipside_silver
    database: flipside_prod_db
    schema: silver
    tables:
      - name: ethereum_contracts_backfill
      - name: ethereum_contracts
  - name: eth_dev_db
    database: ethereum_dev
    schema: silver
    tables:
      - name: aave_atokens_upload
  - name: bronze
    database: flipside_prod_db
    schema: bronze
    tables:
      - name: prod_ethereum_sink_407559501
      - name: bronze_snapshot_719356055
  - name: ethereum_silver
    database: ethereum
    schema: silver
    tables:
      - name: token_meta_backup
      - name: signatures_backfill
      - name: event_signatures_backfill
      - name: aave_atokens_upload
  - name: ethereum_share
    database: "{{target.database}}"
    schema: silver
    tables:
      - name: token_prices_hourly
      - name: dex_liquidity_pools
      - name: labels
  - name: bronze_streamline
    database: "{{target.database}}"
    schema: bronze
    tables:
      - name: token_balances
        pre-hook: ALTER TABLE IF EXISTS bronze.token_balances REFRESH
      - name: eth_balances
        pre-hook: ALTER TABLE IF EXISTS bronze.eth_balances REFRESH
      - name: reads
        pre-hook: ALTER TABLE IF EXISTS bronze.reads REFRESH
  - name: ethereum_external
    schema: silver
    loader: S3
    tables:
      - name: nft_metadata_api
        description: "External table of NFT metadata files"
        external:
          location: "@{{target.database}}.bronze.analytics_external_tables/{{target.database}}/NFT_METADATA_API"
          file_format: "( type = json, strip_outer_array = TRUE )"
          auto_refresh: true # requires configuring an event notification from Amazon S3 or Azure
        columns:
          - name: system_created_at
            data_type: timestamp_ntz
            description: "timestamp for when the record was loaded by api"
            expression: value:system_created_at::string::timestamp_ntz
          - name: blockchain
            data_type: string
            description: "name of blockchain a nft collection was created on. Will always be ethereum in this project"
            expression: value:blockchain::string
          - name: commission_rate
            data_type: float
            description: "commission rate for minting nft"
            expression: value:commission_rate::float
          - name: contract_address
            data_type: string
            description: "address of nft collection"
            expression: value:contract_address::string
          - name: contract_name
            data_type: string
            description: "name of nft collection"
            expression: value:contract_name::string
          - name: created_at_block_id
            data_type: number
            description: "block from which a specific nft was created"
            expression: value:created_at_block_id::number
          - name: created_at_timestamp
            data_type: timestamp_ntz
            description: "timestamp of nft mint"
            expression: value:created_at_timestamp::string::timestamp_ntz
          - name: created_at_tx_id
            data_type: string
            description: "transaction hash where nft was minted"
            expression: value:created_at_tx_id::string
          - name: creator_address
            data_type: string
            description: "address of creator"
            expression: value:creator_address::string
          - name: creator_name
            data_type: string
            description: "creator name"
            expression: value:creator_name::string
          - name: image_url
            data_type: string
            description: "cached url of nft image"
            expression: value:image_url::string
          - name: project_name
            data_type: string
            description: "project name"
            expression: value:project_name::string
          - name: token_id
            data_type: string
            description: "token id of the nft"
            expression: value:token_id::string
          - name: token_metadata
            data_type: object
            description: "attributes of the nft"
            expression: value:token_metadata::object
          - name: token_metadata_uri
            data_type: string
            description: "link to raw nft metadata file"
            expression: value:token_metadata_uri::string
          - name: token_name
            data_type: string
            description: "name of the nft"
            expression: value:token_name::string
  - name: sushi_external
    schema: silver
    loader: S3
    tables:
      - name: sushi_rewards_schedule
        description: "External table of sushi rewards schedule"
        external:
          location: "@{{target.database}}.bronze.analytics_external_tables/{{target.database}}/SUSHI_REWARDS_SCHEDULE"
          file_format: "( type = json )"
          auto_refresh: true # requires configuring an event notification from Amazon S3 or Azure
        columns:
          - name: merkle_root
            data_type: string
            expression: value:merkle_root::string
          - name: token_total
            data_type: string
            expression: value:token_total::string
          - name: claims
            data_type: variant
            expression: value:claims::variant
